loglevel: Debug
write-directory: test_output
write: true
output: yaml
services:
  your-service:
    plugin: {{ .ServiceName }}
    test-suites:
      - your_test_suite
      - your_other_test_suite
    vars:
      your: a
      required: x
      variables: y
