loglevel: Debug
write-directory: test_output
write: true
output: yaml
services:
  your-service:
    plugin: {{ .ServiceName }}
    policy:
      catalogs: ["{{ .Metadata.ID | as_id }}"]
      applicability:{{ range .Metadata.ApplicabilityCategories }}
        - {{ .ID | as_id }}{{ end }}
    vars:
      your: a
      required: x
      variables: y
