loglevel: Debug
write-directory: test_output
write: true
output: yaml
services:
  my-cloud-service1:
    plugin: {{ .ServiceName }}
    test-suites:
      - tlp_red
      # - tlp_amber
      # - tlp_green
      # - tlp_clear
